name: flutter_new_test
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg_icons: ^0.0.1+3
  provider: ^6.0.5
  image_picker: ^0.8.9
  shared_preferences: ^2.1.2
  flutter_secure_storage: ^9.0.0
  go_router: ^13.1.0
  fl_chart: ^0.66.1

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/data.json


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf

          

